name: Build-Snap-Edge

on:
  schedule:
    - cron: '0 */5 * * *'
    - cron: '15 13 * * *'
  push:
    branches: [ edge ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"
    steps:
    - uses: actions/checkout@v2
      with:
        ref: edge
        token: ${{ secrets.PAT }}
    - name: Configure Git
      run: |
        git config --global user.name 'Nightmayr'
        git config --global user.email 'umayr23@gmail.com'
    - name: Checkout versions.json (master)
      run: |
        git fetch
        git checkout -m origin/master versions.json
        cat versions.json
    - name: Set up environment
      run: |
        sudo apt install jq -y
        sudo apt install moreutils -y
    - name: Check latest version
      run: |
        ./.github/scripts/version.sh
      id: version-check
    - name: Already latest version - cancelling
      if: env.BUILD == 'false'
      uses: andymckay/cancel-action@0.2
    - uses: snapcore/action-build@v1
      id: snapcraft
    - uses: actions/upload-artifact@v2
      with:
        name: snap
        path: ${{ steps.snapcraft.outputs.snap }}
#     - name: Testing snap
#       run: |
#         sudo snap install --dangerous ${{ steps.snapcraft.outputs.snap }}
#         snap run chiaki --help
    - uses: snapcore/action-publish@v1
      with:
        store_login: ${{ secrets.STORE_LOGIN }}
        snap: ${{ steps.snapcraft.outputs.snap }}
        release: edge
    - name: updating versions.json
      run: |
        cat versions.json | jq '.edge = "${{ env.LATEST_VERSION }}"' | sponge versions.json
    - name: Committing updated versions.json
      run: |
        git add versions.json
        git commit -m "Updating version [ci-skip]"
        git push origin master
